### ISSUE TITLE
Integration via Arduino IDE

### ISSUE THREAD

**Issue by Beppi4U** [blotfi/ESP32-Radio-with-Spectrum-analyzer#1]
Hello! 
Nice work! Is it possible to integrate the feature with the Arduino IDE.
If the answer is yes...can you Show me how to!?
Greetings
Andi
...by the way i have a 1.8TFT Display via SPI

**Comment by blotfi** [comment]
It works directly with Arduino IDE
you just take what is in src directory, rename Esp32_radio.cpp into Esp32_radio.ino
you install the libraries needed see
https://github.com/Edzelf/ESP32-Radio
for details of this libs
for the display
there is a file called 

    ILI9341.h
you modify:

    #define dsp_getwidth()          320                                // Adjust to your display
    #define dsp_getheight()         240                                // Get height of screen 

Perhaps also

```
scrseg_struct     tftdata[TFTSECS] =                        // Screen divided in 3 segments + 1 overlay
{                                                           // One text line is 8 pixels
  { false, WHITE,   0,  8, "" },    // 1 top line
  { false, CYAN,   20, 64, "" },    // 8 lines in the middle
  { false, YELLOW, 90, 64, "" },    // 4 lines at the bottom
  { false, GREEN,  90, 32, "" }         // 4 lines at the bottom for rotary encoder
} ;

```

**Comment by Beppi4U** [comment]
Hi! Thanks for the fast response!
Will give it a try and send a feedback as soon as possible!
Beppi

**Comment by Beppi4U** [comment]
![18TFT](https://user-images.githubusercontent.com/60713366/83290708-5db6cd80-a1e7-11ea-90b5-87a4ece32181.jpg)
Hmmm! I'm sure i've done something wrong! Screen is inverted and Text Size is two times bigger than usually! 
O.K.: Changed from define BLUETFT to ILI9341   next  changed the screen resolution definitions in ILI9431.h to dsp_getwidth() 160 / dsp_getheight() 128 !
Checked the screen section Definition and turned out it's the same like in BLUETFT !
mhhm! Any idea want went wrong?

**Comment by blotfi** [comment]
for the rotation 
in `ILI9341?h`
`#define dsp_setRotation()       tft->setRotation ( 3 )             // Use landscape format (3 for upside down)`
0, 1, 2 or 3  


for the double size
in Esp32_radio.cpp
`dsp_setTextSize ( 2 ) ; `
put 1 for the smallest size
Enjoy

**Comment by blotfi** [comment]
Subscribe to my Youtube channel
https://www.youtube.com/channel/UCXz-fjR26wZPecy5eZCJa7g/playlists

Scratch in french: https://youtu.be/Y1pRI8Pe72k

Scratch in English: https://youtu.be/Y1pRI8Pe72k

**Comment by Beppi4U** [comment]
![20200529_222310_resized](https://user-images.githubusercontent.com/60713366/83302255-484b9e80-a1fb-11ea-8216-08e4a4b787e8.jpg)
 Hi!
SetRotation  to 1 seems Right. Setting dsp_SetTextSize( 1 ) suits to my small 1.8TFT. But the whole screen is still mirrored and there is no SpecAnalyser!
Maybe TFT section divider is wrong. Didn't i Need another section for the Analyser?

**Comment by blotfi** [comment]
This clearly a config issue of the TFT ILI9341 library
Look into the Adafruit_ILIxxxx code

check also an update to draw the Spectrum bars on all the width of the screen : https://github.com/blotfi/ESP32-Radio-with-Spectrum-analyzer/issues/2#issuecomment-636195433

for the FFT, yes your screen is small
so the bars are appearing down

        uint8_t cur = (cur1*curvol)/30; // big bars
try
        uint8_t cur = (cur1*curvol)/100; // big bars

and
       const uint8_t Spectrum_y0 = 150;
      const uint8_t Spectrum_hy = 70;

Lower these value to 
80
and 35

**Comment by blotfi** [comment]
look at this post
try un connecting then connecting again (POR) your device

and try
```
// Rotation params:
// 0 - 0 deg
// 1 - 90 deg anti-clockwise (from 0 deg)
// 2 - 180 deg anti-clockwise
// 3 - 270 deg anti-clockwise
// 4 - mirror content, and rotate 180 deg anti-clockwise
// 5 - mirror content, and rotate 270 deg anti-clockwise
// 6 - mirror content, and rotate 0 deg anti-clockwise
// 7 - mirror content, and rotate 90 deg anti-clockwise
dsp_setRotation(6);
```

**Comment by Beppi4U** [comment]
Hi there! Thanks for the hints!
We're making Progress but....   Yeah!!!
Getting Spec Analyser -> check  -->dsp_setRotation(1) //see picture  
As you can see the Content is still mirrored - non of the other params worked! ....and the Radio Station is no longer readable. 
![20200530_191826_resized](https://user-images.githubusercontent.com/60713366/83335880-04ff3780-a2b0-11ea-8835-ffe33bc73be4.jpg)

How can i correct this issue. 
In Addition the Volume only appears when you hit the Rotary encoder.  
Greeting 
Andi

**Comment by blotfi** [comment]
the volume bar is not a problem, it is a matter of  finding the right position of
```
scrseg_struct     tftdata[TFTSECS] =                        // Screen divided in 3 segments + 1 overlay
{                                                           // One text line is 8 pixels
  { false, WHITE,   0,  8, "" },    // 1 top line
  { false, CYAN,   20, 32, "" },    //  ?? ines in the middle
  { false, YELLOW, 90, 32, "" },    // ?? lines at the bottom
  { false, GREEN,  90, 32, "" }         // 4 lines at the bottom for rotary encoder
} ;
```
and also putting small Spectrum bands

for the inverted text,
try ALL the possibilities of `dsp_setRotation(x);`  from 0 to 7

**Comment by Beppi4U** [comment]
After a lot of cross checking and comparing the ILI files via notepad++ i noticed that i do NOT have an ILI9431 Display! I knew that before but thougt i need it for showing the analyser.
Activating BlueTFT instead of ILI9431 did the trick ! 
Now i feel a Little bit dumb! I need a beer or two!
Thanks for the effort and helping me out on this! 
Cheers!
 Andi
![TFT](https://user-images.githubusercontent.com/60713366/83337959-ebfe8280-a2bf-11ea-802c-4a3c0dd9b782.jpg)

**Comment by Beppi4U** [comment]
Last Thing to do is to bring back the Radiostation Text to screen! ;-)

**Comment by blotfi** [comment]
try that and play with the values
```
scrseg_struct     tftdata[TFTSECS] =                        // Screen divided in 3 segments + 1 overlay
{                                                           // One text line is 8 pixels
  { false, WHITE,   0,  8, "" },    // 1 top line
  { false, CYAN,   10, 32, "" },    //  ?? ines in the middle
  { false, YELLOW, 30, 32, "" },    // ?? lines at the bottom
  { false, GREEN,  30, 32, "" }         // 4 lines at the bottom for rotary encoder
} ;
```

also push you time to the right more than in my code
`#define TIMEPOS -92`
to
`#define TIMEPOS -60`
or less

**Comment by blotfi** [comment]
you didn't update your bar display routines to put it full on the width of the screen

https://github.com/blotfi/ESP32-Radio-with-Spectrum-analyzer/issues/2#issuecomment-636195433

**Comment by Beppi4U** [comment]
Simply modified as you told me and  finally .....tada! It works ! ;-) 
Thanks for helping me! 
![Finally](https://user-images.githubusercontent.com/60713366/83351013-c8c7e780-a340-11ea-93c1-5af6d5e807eb.jpg)
 
Will there be a Chance that Ed will include this in his main Fork? Did you showed him this? 
Greetings
Andi

**Comment by johnaweiss** [comment]
> Now i feel a Little bit dumb! I need a beer or two!

not sure beer will make you smarter :D
