### ISSUE TITLE
System Power consumption?

### ISSUE THREAD

**Issue by Beppi4U** [blotfi/ESP32-Radio-with-Spectrum-analyzer#3]
Any experiences with power consumption?
Will be a 5V 2Amps Power supply be enough for the System and a PAM amplifier?
Want to try out a breadboard power Adapter like HW-131. 
Greetings 
Andi

**Comment by blotfi** [comment]
You need to see with the original Github
for the ESP32+TFT, 2A is more than enough, but for the Amplifier and the speakers I don't know, it depends on their power
