### ISSUE TITLE
How to Load VS1053b Plugin?

### ISSUE THREAD

**Issue by johnaweiss** [blotfi/ESP32-Radio-with-Spectrum-analyzer#5]
Hi, i hope you can help. I can't figure out how to load the spectrum analyzer plugin into the VS1053b. 

Is that done with the uC?

Are you using an arduino library for the 1053b?

thx!

**Comment by blotfi** [comment]
> Hi, i hope you can help. I can't figure out how to load the spectrum analyzer plugin into the VS1053b.
> 
> Is that done with the uC?
exact, you have nothing to do,
when the program starts, there is a function that is called and the ESP32 will load the plugin on the VS1053b

> 
> Are you using an arduino library for the 1053b?
??? no
use the program provided
> 
> thx!
