### ISSUE TITLE
MP3 Player Malfunction

### ISSUE THREAD

**Issue by patrice86** [blotfi/ESP32-Radio-with-Spectrum-analyzer#6]
Hello,
Thank you for your project, it is really very well done, I am a great beginner in programming.
I nevertheless succeeded in adapting this project but I encountered an anomaly in the functioning of the web MP3 Player. My knowledge being very weak in web could you help me.
![image](https://user-images.githubusercontent.com/39810300/99910491-9e9f2300-2cee-11eb-8210-ad6220c083be.png)

**Comment by blotfi** [comment]
Hi
You have a simple problem of naming convention
use only ASCII code for naming, no special symbols, spaces,...
So you have to rename all the mp3 files , that come always with fancy characters

**Comment by patrice86** [comment]
Hello,
Thank you for having the time to answer me,
I tried to rename all the files on the card by removing the non-uniform characters but this is the same,
and nothing on the display on the current song ...
Do you have another idea?
![image](https://user-images.githubusercontent.com/39810300/100007416-56563280-2dcc-11eb-85e0-024d31800de8.png)

**Comment by patrice86** [comment]
Hello,
Thank you for having the time to answer me,
I tried to rename all the files on the card by removing the non-uniform characters but this is the same,
and nothing on the display on the current song ...
Do you have another idea?
![image](https://user-images.githubusercontent.com/39810300/100007416-56563280-2dcc-11eb-85e0-024d31800de8.png)

**Comment by blotfi** [comment]
Try only 2 mp3 files with 8.3 filename format in the root of the sdcard
Format the sdcard in fat32 or fat16

**Comment by patrice86** [comment]
Good evening Blotfi,
Thanks for your advice, I tried to rename to 8.3 format, make the name as small as possible, but nothing promising.
My SDCard is 2GB, I have no less ... (test in FAT16 and FAT32)
After all nothing to worry about because it is only for the radio WEB site.
Thank you for your time.
I will order a different SDCard module which is not related to the KMR-1.8 for testing.
